// Mock data for My Tutor+ LMS prototype
import { 
  User, Course, Enrollment, Lesson, LiveSession, 
  Assignment, Submission, Quiz, Payment, Notification,
  Message, Attendance, Analytics 
} from '../types';

// Current mock user (can be switched for different roles)
export let currentUser: User = {
  id: 'student-1',
  email: 'adebayo.james@student.com',
  firstName: 'James',
  lastName: 'Adebayo',
  role: 'student',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
  phoneNumber: '+234 803 123 4567',
  classLevel: 'SS2',
  createdAt: '2024-09-01T00:00:00Z',
};

export const setCurrentUser = (user: User) => {
  currentUser = user;
};

export const mockUsers: User[] = [
  currentUser,
  {
    id: 'instructor-1',
    email: 'prof.okonkwo@tutor.com',
    firstName: 'Chidi',
    lastName: 'Okonkwo',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chidi',
    phoneNumber: '+234 802 987 6543',
    createdAt: '2024-01-15T00:00:00Z',
    isActive: true,
  },
  {
    id: 'admin-1',
    email: 'admin@tutorplus.com',
    firstName: 'Fatima',
    lastName: 'Yusuf',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
    phoneNumber: '+234 801 234 5678',
    createdAt: '2024-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-2',
    email: 'blessing.okafor@student.com',
    firstName: 'Blessing',
    lastName: 'Okafor',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Blessing',
    phoneNumber: '+234 803 456 7890',
    classLevel: 'SS3',
    createdAt: '2024-09-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-3',
    email: 'tunde.bello@student.com',
    firstName: 'Tunde',
    lastName: 'Bello',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tunde',
    phoneNumber: '+234 805 123 4567',
    classLevel: 'SS1',
    createdAt: '2024-09-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'instructor-2',
    email: 'mrs.adeyemi@tutor.com',
    firstName: 'Funke',
    lastName: 'Adeyemi',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Funke',
    phoneNumber: '+234 806 789 0123',
    createdAt: '2024-02-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-4',
    email: 'chioma.nwankwo@student.com',
    firstName: 'Chioma',
    lastName: 'Nwankwo',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chioma',
    phoneNumber: '+234 807 234 5678',
    classLevel: 'SS2',
    createdAt: '2024-10-05T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-5',
    email: 'samuel.okeke@student.com',
    firstName: 'Samuel',
    lastName: 'Okeke',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Samuel',
    phoneNumber: '+234 808 345 6789',
    classLevel: 'SS1',
    createdAt: '2024-09-15T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-6',
    email: 'aisha.ibrahim@student.com',
    firstName: 'Aisha',
    lastName: 'Ibrahim',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha',
    phoneNumber: '+234 809 456 7890',
    classLevel: 'SS3',
    createdAt: '2024-08-20T00:00:00Z',
    isActive: false,
  },
  {
    id: 'instructor-3',
    email: 'dr.musa@tutor.com',
    firstName: 'Musa',
    lastName: 'Ahmed',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Musa',
    phoneNumber: '+234 810 567 8901',
    createdAt: '2024-03-10T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-7',
    email: 'ngozi.eze@student.com',
    firstName: 'Ngozi',
    lastName: 'Eze',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ngozi',
    phoneNumber: '+234 811 678 9012',
    classLevel: 'SS2',
    createdAt: '2024-09-25T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-8',
    email: 'michael.obi@student.com',
    firstName: 'Michael',
    lastName: 'Obi',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    phoneNumber: '+234 812 789 0123',
    classLevel: 'SS1',
    createdAt: '2024-10-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-9',
    email: 'esther.daniel@student.com',
    firstName: 'Esther',
    lastName: 'Daniel',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Esther',
    phoneNumber: '+234 813 890 1234',
    classLevel: 'SS3',
    createdAt: '2024-09-10T00:00:00Z',
    isActive: true,
  },
  {
    id: 'instructor-4',
    email: 'prof.williams@tutor.com',
    firstName: 'Williams',
    lastName: 'Johnson',
    role: 'instructor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Williams',
    phoneNumber: '+234 814 901 2345',
    createdAt: '2024-04-05T00:00:00Z',
    isActive: true,
  },
  {
    id: 'student-10',
    email: 'folake.adebayo@student.com',
    firstName: 'Folake',
    lastName: 'Adebayo',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Folake',
    phoneNumber: '+234 815 012 3456',
    classLevel: 'SS2',
    createdAt: '2024-10-10T00:00:00Z',
    isActive: false,
  },
];

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Advanced Mathematics for SS2',
    description: 'Comprehensive mathematics course covering algebra, geometry, and trigonometry for SS2 students preparing for WAEC and NECO.',
    thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80',
    instructorId: 'instructor-1',
    instructorName: 'Prof. Chidi Okonkwo',
    price: 15000,
    currency: 'NGN',
    category: 'Mathematics',
    level: ['SS2'],
    duration: '12 weeks',
    enrollmentCount: 142,
    rating: 4.8,
    isPublished: true,
    createdAt: '2024-08-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'course-2',
    title: 'English Language & Literature',
    description: 'Master English comprehension, essay writing, and literature analysis for SS1-SS3 students.',
    thumbnail: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80',
    instructorId: 'instructor-2',
    instructorName: 'Mrs. Funke Adeyemi',
    price: 12000,
    currency: 'NGN',
    category: 'English',
    level: ['SS1', 'SS2', 'SS3'],
    duration: '10 weeks',
    enrollmentCount: 256,
    rating: 4.9,
    isPublished: true,
    createdAt: '2024-07-15T00:00:00Z',
    updatedAt: '2024-10-15T00:00:00Z',
  },
  {
    id: 'course-3',
    title: 'Physics for SS3 - WAEC Preparation',
    description: 'Complete physics course focusing on WAEC syllabus with practical experiments and problem-solving.',
    thumbnail: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=800&q=80',
    instructorId: 'instructor-1',
    instructorName: 'Prof. Chidi Okonkwo',
    price: 18000,
    currency: 'NGN',
    category: 'Science',
    level: ['SS3'],
    duration: '14 weeks',
    enrollmentCount: 98,
    rating: 4.7,
    isPublished: true,
    createdAt: '2024-08-10T00:00:00Z',
    updatedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'course-4',
    title: 'Chemistry Fundamentals - SS1',
    description: 'Introduction to chemistry covering atomic structure, chemical bonding, and basic reactions.',
    thumbnail: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=800&q=80',
    instructorId: 'instructor-2',
    instructorName: 'Mrs. Funke Adeyemi',
    price: 14000,
    currency: 'NGN',
    category: 'Science',
    level: ['SS1'],
    duration: '12 weeks',
    enrollmentCount: 187,
    rating: 4.6,
    isPublished: true,
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: 'course-5',
    title: 'Computer Science & Programming',
    description: 'Learn programming basics with Python, web development fundamentals, and computer science concepts.',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
    instructorId: 'instructor-1',
    instructorName: 'Prof. Chidi Okonkwo',
    price: 20000,
    currency: 'NGN',
    category: 'Technology',
    level: ['SS2', 'SS3'],
    duration: '16 weeks',
    enrollmentCount: 203,
    rating: 4.9,
    isPublished: true,
    createdAt: '2024-07-01T00:00:00Z',
    updatedAt: '2024-10-01T00:00:00Z',
  },
  {
    id: 'course-6',
    title: 'Biology & Life Sciences',
    description: 'Comprehensive biology course covering cell biology, genetics, ecology, and human anatomy.',
    thumbnail: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=800&q=80',
    instructorId: 'instructor-2',
    instructorName: 'Mrs. Funke Adeyemi',
    price: 16000,
    currency: 'NGN',
    category: 'Science',
    level: ['SS2', 'SS3'],
    duration: '14 weeks',
    enrollmentCount: 164,
    rating: 4.8,
    isPublished: true,
    createdAt: '2024-08-15T00:00:00Z',
    updatedAt: '2024-11-05T00:00:00Z',
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: 'enroll-1',
    studentId: 'student-1',
    courseId: 'course-1',
    enrolledAt: '2024-09-15T00:00:00Z',
    status: 'active',
    progress: 68,
    lastAccessedAt: '2024-11-16T14:30:00Z',
  },
  {
    id: 'enroll-2',
    studentId: 'student-1',
    courseId: 'course-2',
    enrolledAt: '2024-09-20T00:00:00Z',
    status: 'active',
    progress: 45,
    lastAccessedAt: '2024-11-15T10:20:00Z',
  },
  {
    id: 'enroll-3',
    studentId: 'student-1',
    courseId: 'course-5',
    enrolledAt: '2024-10-01T00:00:00Z',
    status: 'active',
    progress: 32,
    lastAccessedAt: '2024-11-14T16:45:00Z',
  },
];

export const mockLessons: Lesson[] = [
  {
    id: 'lesson-1',
    courseId: 'course-1',
    title: 'Introduction to Quadratic Equations',
    description: 'Learn the fundamentals of quadratic equations and how to solve them.',
    type: 'recorded',
    duration: 45,
    order: 1,
    videoUrl: 'https://example.com/video-1',
    resources: [
      { id: 'res-1', name: 'Quadratic Equations Notes.pdf', type: 'pdf', url: '#' },
      { id: 'res-2', name: 'Practice Problems.pdf', type: 'pdf', url: '#' },
    ],
    isPublished: true,
  },
  {
    id: 'lesson-2',
    courseId: 'course-1',
    title: 'Solving Complex Quadratic Problems',
    description: 'Advanced techniques for solving complex quadratic equations.',
    type: 'live',
    duration: 60,
    order: 2,
    resources: [],
    isPublished: true,
  },
  {
    id: 'lesson-3',
    courseId: 'course-1',
    title: 'Trigonometry Basics',
    description: 'Understanding sine, cosine, and tangent functions.',
    type: 'recorded',
    duration: 50,
    order: 3,
    videoUrl: 'https://example.com/video-3',
    resources: [
      { id: 'res-3', name: 'Trigonometry Formulas.pdf', type: 'pdf', url: '#' },
    ],
    isPublished: true,
  },
];

export const mockLiveSessions: LiveSession[] = [
  {
    id: 'session-1',
    lessonId: 'lesson-2',
    courseId: 'course-1',
    title: 'Live: Solving Complex Quadratic Problems',
    scheduledAt: '2024-11-18T14:00:00Z',
    duration: 60,
    meetingUrl: 'https://meet.tutorplus.com/session-1',
    status: 'scheduled',
    attendees: [],
  },
  {
    id: 'session-2',
    lessonId: 'lesson-5',
    courseId: 'course-2',
    title: 'Live: Essay Writing Workshop',
    scheduledAt: '2024-11-19T10:00:00Z',
    duration: 90,
    meetingUrl: 'https://meet.tutorplus.com/session-2',
    status: 'scheduled',
    attendees: [],
  },
  {
    id: 'session-3',
    lessonId: 'lesson-8',
    courseId: 'course-5',
    title: 'Live: Python Programming Basics',
    scheduledAt: '2024-11-20T15:00:00Z',
    duration: 75,
    meetingUrl: 'https://meet.tutorplus.com/session-3',
    status: 'scheduled',
    attendees: [],
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'assign-1',
    courseId: 'course-1',
    title: 'Quadratic Equations Problem Set',
    description: 'Solve the 10 quadratic equation problems in the attached worksheet.',
    dueDate: '2024-11-22T23:59:00Z',
    totalPoints: 100,
    attachments: [
      { id: 'att-1', name: 'Problem Set.pdf', type: 'pdf', url: '#' },
    ],
    createdAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'assign-2',
    courseId: 'course-2',
    title: 'Persuasive Essay on Climate Change',
    description: 'Write a 500-word persuasive essay on climate change and its effects.',
    dueDate: '2024-11-25T23:59:00Z',
    totalPoints: 50,
    attachments: [],
    createdAt: '2024-11-12T00:00:00Z',
  },
  {
    id: 'assign-3',
    courseId: 'course-5',
    title: 'Build a Simple Calculator',
    description: 'Create a command-line calculator using Python that can perform basic arithmetic operations.',
    dueDate: '2024-11-28T23:59:00Z',
    totalPoints: 100,
    attachments: [
      { id: 'att-2', name: 'Requirements.pdf', type: 'pdf', url: '#' },
    ],
    createdAt: '2024-11-14T00:00:00Z',
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-1',
    assignmentId: 'assign-1',
    studentId: 'student-2',
    studentName: 'Blessing Okafor',
    content: 'Submitted solutions to all 10 problems.',
    attachments: [
      { id: 'att-3', name: 'My Solutions.pdf', type: 'pdf', url: '#' },
    ],
    submittedAt: '2024-11-16T18:30:00Z',
    grade: 85,
    feedback: 'Great work! Minor errors in problems 7 and 9.',
    gradedAt: '2024-11-17T09:00:00Z',
    status: 'graded',
  },
  {
    id: 'sub-2',
    assignmentId: 'assign-1',
    studentId: 'student-3',
    studentName: 'Tunde Bello',
    content: 'Here are my answers.',
    attachments: [
      { id: 'att-4', name: 'Answers.pdf', type: 'pdf', url: '#' },
    ],
    submittedAt: '2024-11-17T20:15:00Z',
    status: 'submitted',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay-1',
    studentId: 'student-1',
    courseId: 'course-1',
    amount: 15000,
    currency: 'NGN',
    status: 'completed',
    paymentMethod: 'paystack',
    reference: 'TXN-20240915-001',
    paidAt: '2024-09-15T12:30:00Z',
    createdAt: '2024-09-15T12:00:00Z',
  },
  {
    id: 'pay-2',
    studentId: 'student-1',
    courseId: 'course-2',
    amount: 12000,
    currency: 'NGN',
    status: 'completed',
    paymentMethod: 'flutterwave',
    reference: 'TXN-20240920-002',
    paidAt: '2024-09-20T14:20:00Z',
    createdAt: '2024-09-20T14:00:00Z',
  },
  {
    id: 'pay-3',
    studentId: 'student-1',
    courseId: 'course-5',
    amount: 20000,
    currency: 'NGN',
    status: 'completed',
    paymentMethod: 'paystack',
    reference: 'TXN-20241001-003',
    paidAt: '2024-10-01T10:15:00Z',
    createdAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'pay-4',
    studentId: 'student-2',
    courseId: 'course-3',
    amount: 18000,
    currency: 'NGN',
    status: 'pending',
    paymentMethod: 'paystack',
    reference: 'TXN-20241120-004',
    createdAt: '2024-11-20T09:30:00Z',
  },
  {
    id: 'pay-5',
    studentId: 'student-2',
    courseId: 'course-4',
    amount: 25000,
    currency: 'NGN',
    status: 'completed',
    paymentMethod: 'stripe',
    reference: 'TXN-20241015-005',
    paidAt: '2024-10-15T16:45:00Z',
    createdAt: '2024-10-15T16:30:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'student-1',
    title: 'New Assignment Posted',
    message: 'A new assignment has been posted in Advanced Mathematics for SS2',
    type: 'info',
    isRead: false,
    createdAt: '2024-11-14T09:00:00Z',
    link: '/student/courses/course-1/assignments',
  },
  {
    id: 'notif-2',
    userId: 'student-1',
    title: 'Upcoming Live Class',
    message: 'Live class "Solving Complex Quadratic Problems" starts in 2 days',
    type: 'warning',
    isRead: false,
    createdAt: '2024-11-16T10:00:00Z',
    link: '/student/schedule',
  },
  {
    id: 'notif-3',
    userId: 'student-1',
    title: 'Payment Successful',
    message: 'Your payment of ₦20,000 for Computer Science & Programming has been confirmed',
    type: 'success',
    isRead: true,
    createdAt: '2024-10-01T10:20:00Z',
    link: '/student/payments',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    senderId: 'instructor-1',
    senderName: 'Prof. Chidi Okonkwo',
    recipientId: 'student-1',
    subject: 'Regarding Assignment 1',
    content: 'Hello James, I noticed you haven\'t submitted Assignment 1 yet. Please let me know if you need any help.',
    isRead: false,
    sentAt: '2024-11-15T16:30:00Z',
  },
  {
    id: 'msg-2',
    senderId: 'admin-1',
    senderName: 'Admin Team',
    recipientId: 'student-1',
    subject: 'Welcome to My Tutor+',
    content: 'Welcome to My Tutor+! We\'re excited to have you. If you need any help, feel free to reach out.',
    isRead: true,
    sentAt: '2024-09-01T08:00:00Z',
  },
];

export const mockAnalytics: Analytics = {
  totalRevenue: 8450000,
  totalStudents: 1247,
  totalInstructors: 38,
  totalCourses: 156,
  activeEnrollments: 3842,
  completionRate: 72.5,
  averageRating: 4.7,
  revenueGrowth: 23.4,
};

// Helper functions
export const getCourseById = (id: string) => mockCourses.find(c => c.id === id);
export const getUserById = (id: string) => mockUsers.find(u => u.id === id);
export const getEnrolledCourses = (studentId: string) => {
  const enrollments = mockEnrollments.filter(e => e.studentId === studentId);
  return enrollments.map(e => ({
    ...getCourseById(e.courseId)!,
    enrollment: e,
  }));
};
export const getCoursesByInstructor = (instructorId: string) => 
  mockCourses.filter(c => c.instructorId === instructorId);
